[package]
name = "dcr"
version = "0.1.0"
edition = "2021"
description = "DICOM TUI Viewer"

[dependencies]
ratatui = "0.29"
crossterm = "0.28"
dicom = "0.8"
clap = { version = "4.5", features = ["derive"] }
